### ISSUE TITLE
Cursor fade causes text flicker

### ISSUE THREAD

**Issue by brentd** [brentd/neutron-syntax#4]
The fading/pulsing of the cursor with `transition: opacity 0.3s` appears to be causing text aliasing flicker in the project sidebar, but only if the main window is overlapping its content.

Forcing `font-smoothing` to the less desirable (IMO) setting of `antialiased` relieves the issue:

``` css
.tree-view {
  -webkit-font-smoothing: antialiased;
}
```

Forcing GPU rendering with something like `-webkit-backface-visibility: hidden` seems to have the same effect as the above.
